const quotes = [
    "Lift it. Text it. Love it.",
    "Každý rep je krok blíž k cíli.",
    "Ticho? Ne. To je jen soustředěná bouře.",
    "Silné tělo, ještě silnější hlava.",
    "Není to o tom, kolik zvedneš. Ale že to nevzdáš.",
    "Zvedáš činky. Zvedáš sebe.",
    "Nejsilnější část těla? Tvůj mindset.",
    "Každý pot má smysl.",
    "Zvednuto není jen appka. Je to stav mysli.",
    "Každý den, kdy makáš, jsi dál než včera.",
    "Dokážeš to. A pak to uděláš znovu.",
    "Make muscles, not excuses.",
    "Lvi necvičí, aby byli roztomilí. Cvičí, aby byli neporazitelní.",
    "Hydratuj. Zvedej. Zář.",
    "Každý začátek je těžký. Ale ty jsi těžší kalibr.",
    "Dřepni si – a ukaž, co v tobě je.",
    "Překonej výmluvy. Přepiš limity.",
    "Trénink není trest. Je to privilegium.",
    "Jsi silnější, než si myslíš. A krásnější, než víš.",
    "Nepotřebuješ motivaci. Potřebuješ rozhodnutí.",
    "Make sweat your best accessory.",
    "Zvedej srdcem, ne jen svaly.",
    "I když padneš – spadneš dopředu. A to je pokrok.",
    "No excuses. Just execution.",
    "Nech činky mluvit za tebe.",
    "Tvůj stín dnes maká, aby zítra svítil.",
    "Cvičení není povinnost. Je to tvoje zbraň.",
    "Když pálí nohy, rodí se lví stehna.",
    "ZVEDNUTO je víc než appka – je to tvůj podpis síly.",
    "V každém dřepu – nový level respektu.",
    "Push harder. Glow louder.",
    "Zvedni. Ulož. A příště víc.",
    "Tvůj progress není hlasitý, ale nepřehlédnutelný.",
    "Jedna činka. Jeden mindset. Nula výmluv.",
    "Zvedej s grácií. Plač s hrdostí. Vrať se silnější.",
    "Zvedni se. Zvedni to. Zvedni sebe.",
    "Zvedání není sport. Je to posvátný rituál bouře.",
    "Když nevíš, zeptej se činky. Ona ti odpoví.",
    "Váha není nepřítel. Je to výzva.",
    "Pocit, když to zvedneš, je lepší než cheat day.",
    "Storm inside. Form outside.",
    "Nevypadáš silně. Ty silný prostě jsi.",
    "Každá kapka potu je podpisem tvé disciplíny.",
    "Make the mirror your rival, not your goal.",
    "ZVEDNUTO není jen logo. Je to režim.",
    "Nepřestávej, když to bolí. Přestaň, až to vypadá božsky.",
    "Tohle není jen workout. Tohle je výpis tvé osobnosti.",
    "Mám sílu. Mám styl. Mám ZVEDNUTO.",
    "Někdo si píše deník. Já si ho odcvičím.",
    "Nezvedám váhu. Zvedám standardy.",
    "Každá série je hlasité NE pohodlnosti.",
    "Síla začíná v hlavě. A pak to poznáš na kalhotách.",
    "Make your glutes salute. 🍑",
    "Dneska necvičím pro zrcadlo. Cvičím, protože můžu.",
    "Tenhle pot? Luxusní parfém výsledků.",
    "Máš na to. A pak ještě trochu víc.",
    "Všichni říkají 'běž pomalu'. Já říkám – běž jako bouře.",
    "Jeden dřep za disciplínu. Jeden výdech za vděčnost.",
    "Největší PR je, že jsi to nevzdala.",
    "ZVEDNUTO není jen slovo. Je to restart režimu."
  ];

  export const MotivationalQuote = () => {
    const random = Math.floor(Math.random() * quotes.length);
    const quote = quotes[random];
  
    return <p className="citaty">„{quote}“</p>;
  };